Remove android.hardware.power-impl
This is required to compile PixelOS properly.

Error: makefile error
Output:
build/make/core/main.mk:1377: warning: device/oneplus/guacamoleb/aosp_guacamoleb.mk includes non-existent modules in PRODUCT_PACKAGES
Offending entries:
android.hardware.power-impl